# Problem Sets {#psets}

::: {.exercise #lqrconstraints name="LQR with Constraints"}
Consider a variant of the LQR problem \@ref(eq:lqr-formulation) where the controls are bounded between $[-u_{\max}, u_{\max}]$, the system matrices $A_k, B_k$ are constant, and the dynamics is deterministic:
\begin{equation}
\begin{split}
J(x_0) = \min_{u_{0},\dots,u_{N-1} \in [-u_{\max},u_{\max}]} &\quad  x_N^T Q_N x_N + \sum_{k=0}^{N-1} (x_k^T Q_k x_k + u_k^T R_k u_k) \\
\text{subject to} &\quad  x_{k+1} = A x_k + B u_k,  k=0,\dots,N-1
\end{split}
(\#eq:lqr-constraints)
\end{equation}
We assume $Q_k\succeq 0$ for $k=0,\dots,N$ and $R_k \succ 0$ for all $k=0,\dots,N-1$.

a. Show that Problem \@ref(eq:lqr-constraints), when $x_0$ is given, is a convex optimization problem.

b. Discretize the continuous-time double integrator dynamics
$$
\ddot{q} = u, \quad u \in [-1,1]
$$
in the form of $x_{k+1} = A x_k + B u_k$ with a constant $dt$ time discretization. (Hint: take $x = [q,\dot{q}]$ as the state vector.)

c. Fix $N=50$, $dt=0.1$ and choose your favorite $Q_k$ and $R_k$. Solve the convex optimization \@ref(eq:lqr-constraints) at a dense grid of $x_0$. Plot $J(x_0)$. (Hint: you will most likely benefit from Appendix \@ref(appconvex-practice).)

d. Increase $N$ and decrease $dt$, plot $J(x_0)$ for different pairs of $(N,dt)$. What do you observe?

e. (Bonus) Can you write down the KKT optimality conditions of \@ref(eq:lqr-constraints) and explain what you have observed from the numerical experiment? (Hint: KKT optimality conditions can be found in Theorem \@ref(thm:KKT).)
:::

::: {.exercise #lqrmanifold name="LQR on A Manifold"}
LQR [@saccon13tac-lie] [@teng22cdc-lie]
:::