name: Build and Deploy Book

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Setup R
        uses: r-lib/actions/setup-r

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc

      - name: Setup Tinytex
        uses: r-lib/actions/setup-tinytex

      - name: Install dependencies
        run: |
          install.packages("bookdown")

      - name: Build book
        run: ./_build.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book

